language: node_js
node_js:
  - "6"
before_install:
  # setting the path for phantom.js 2.0.0
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g @angular/cli
script:
  - npm run-script build:dist
  - npm run-script test:coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)