language: node_js
node_js:
  - "6"
before_install:
  # setting the path for phantom.js 2.0.0
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages
script:
  - npm run-script build4prod
  - npm run-script test4ci
  - export BRANCH_NAME=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - if [ "$BRANCH_NAME" == "master" ]; then
      ngh --repo=https://GH_TOKEN@github.com/oasp/oasp4js-ng-project-seed.git --name="oasp4js-build" --email=GH_EMAIL;
    fi
after_success:
  - bash <(curl -s https://codecov.io/bash)